#!/usr/bin/env bash
# Firebase プロジェクト作成・Hosting 設定スクリプト
# Usage: ./scripts/create-firebase-project.sh <display-name> [project-id] [public-dir]
#
#   display-name : アプリの表示名（例: "My App"）
#   project-id   : Firebase プロジェクト ID（省略時は display-name から自動生成）
#   public-dir   : ビルド出力ディレクトリ（省略時は自動検出、見つからなければ dist）

set -euo pipefail

# ─── 引数 ────────────────────────────────────────────────────
DISPLAY_NAME="${1:-}"
PROJECT_ID="${2:-}"
PUBLIC_DIR="${3:-}"

# ─── ヘルプ ──────────────────────────────────────────────────
if [ -z "$DISPLAY_NAME" ] || [ "$DISPLAY_NAME" = "-h" ] || [ "$DISPLAY_NAME" = "--help" ]; then
  echo "Usage: $0 <display-name> [project-id] [public-dir]"
  echo ""
  echo "  display-name  アプリの表示名（例: 'My App'）"
  echo "  project-id    Firebase プロジェクト ID（省略時は自動生成）"
  echo "  public-dir    ビルド出力ディレクトリ（省略時は dist / build / out を自動検出）"
  echo ""
  echo "Examples:"
  echo "  $0 'My Todo App'"
  echo "  $0 'My Todo App' my-todo-app-prod"
  echo "  $0 'My Todo App' my-todo-app-prod dist"
  exit 0
fi

# ─── Firebase CLI チェック ────────────────────────────────────
if ! command -v firebase &> /dev/null; then
  echo "❌ Firebase CLI が見つかりません。インストールしてください:"
  echo "   npm install -g firebase-tools"
  exit 1
fi

# ─── ログイン確認 ─────────────────────────────────────────────
echo "🔑 Firebase ログイン状態を確認中..."
if ! firebase login:list 2>/dev/null | grep -q "@"; then
  echo "  未ログインです。ブラウザでログインしてください。"
  firebase login
fi

# ─── プロジェクト ID 生成 ─────────────────────────────────────
if [ -z "$PROJECT_ID" ]; then
  # 小文字・英数字・ハイフンのみ、先頭は英字、末尾はハイフン不可
  BASE=$(echo "$DISPLAY_NAME" \
    | tr '[:upper:]' '[:lower:]' \
    | tr -cs 'a-z0-9' '-' \
    | sed 's/^-//;s/-$//')
  # 先頭が数字の場合は "app-" を付与
  [[ "$BASE" =~ ^[0-9] ]] && BASE="app-${BASE}"
  # 24文字に切り詰め（末尾サフィックス用に余裕を持たせる）
  BASE="${BASE:0:24}"
  BASE="${BASE%-}"  # 切り詰め後の末尾ハイフンを除去
  SUFFIX=$(date +%s | tail -c 5)
  PROJECT_ID="${BASE}-${SUFFIX}"
fi

# Firebase プロジェクト ID の制約チェック（6〜30文字）
ID_LEN=${#PROJECT_ID}
if [ "$ID_LEN" -lt 6 ] || [ "$ID_LEN" -gt 30 ]; then
  echo "❌ プロジェクト ID の長さが不正です（6〜30文字）: '$PROJECT_ID' (${ID_LEN}文字)"
  exit 1
fi

# ─── ビルドディレクトリ自動検出 ──────────────────────────────
if [ -z "$PUBLIC_DIR" ]; then
  if [ -d "dist" ]; then
    PUBLIC_DIR="dist"
  elif [ -d "build" ]; then
    PUBLIC_DIR="build"
  elif [ -d "out" ]; then
    PUBLIC_DIR="out"
  else
    PUBLIC_DIR="dist"
    echo "⚠️  ビルドディレクトリが見つかりません。'dist' をデフォルトに設定します。"
    echo "   デプロイ前に 'npm run build' でビルドしてください。"
  fi
fi

echo ""
echo "📦 Firebase プロジェクトを作成します"
echo "   表示名       : $DISPLAY_NAME"
echo "   プロジェクト : $PROJECT_ID"
echo "   公開ディレクトリ: $PUBLIC_DIR"
echo ""

# ─── プロジェクト作成 ─────────────────────────────────────────
firebase projects:create "$PROJECT_ID" --display-name "$DISPLAY_NAME"
echo "✅ プロジェクト作成完了: $PROJECT_ID"

# ─── .firebaserc 生成 ─────────────────────────────────────────
cat > .firebaserc <<EOF
{
  "projects": {
    "default": "$PROJECT_ID"
  }
}
EOF
echo "✅ .firebaserc を生成しました"

# ─── firebase.json 生成 ───────────────────────────────────────
cat > firebase.json <<EOF
{
  "hosting": {
    "public": "$PUBLIC_DIR",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
EOF
echo "✅ firebase.json を生成しました（public: $PUBLIC_DIR）"

# ─── Hosting URL を記録 ───────────────────────────────────────
HOSTING_URL="https://${PROJECT_ID}.web.app"
ALT_URL="https://${PROJECT_ID}.firebaseapp.com"

mkdir -p docs/release
cat > docs/release/firebase-url.md <<EOF
# Firebase Hosting URL

| 項目 | 値 |
|------|-----|
| プロジェクト ID | \`$PROJECT_ID\` |
| 表示名 | $DISPLAY_NAME |
| 公開 URL | $HOSTING_URL |
| 代替 URL | $ALT_URL |
| 公開ディレクトリ | \`$PUBLIC_DIR\` |

> Generated by scripts/create-firebase-project.sh
EOF
echo "✅ docs/release/firebase-url.md を生成しました"

# ─── 完了メッセージ ───────────────────────────────────────────
echo ""
echo "🎉 セットアップ完了！"
echo ""
echo "次のステップ:"
echo "  1. アプリをビルド  : npm run build"
echo "  2. Hosting にデプロイ: firebase deploy --only hosting"
echo "  3. 公開 URL        : $HOSTING_URL"
